name: PipelineWorkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipeline@v1
      with:
        azure-devops-project-url: https://dev.azure.com/sarangandrajupalli1/AgileProject/
        azure-pipeline-name: 'WebApplication4'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}